### PR TITLE
Fixed local (non-docker) version of pdf-generator-service

### PR DESCRIPTION
**Pull request by gabrieloczkowski**
Fixed local (non-docker) version of pdf-generator-service;
Moved managing phantom binary to gulp (removed from Dockerfile and ansible-playbooks);
Added binary for macos;
Updated README to meet requirements of the lates macos;

### CODE REVIEW

**Comment by tkopczuk** [comment]
What's the reason for this change? I think it belongs in the Dockerfile - my main reason being - we're using binary, so it'll work only with the runtime library versions it was compiled for. Other Alpine or other Ubuntu version might break it. Here we're moving infrastructure-dependent piece deeper into the source code itself.

**Comment by gabrieloczkowski** [comment]
Reasons:
- wanted to provide non-docker version of app
- maintain phantom prebuilds in one place for docker/non-docker versions

We can try refactor everything to phantomjs-prebuilt (https://github.com/Medium/phantomjs) or start providing only dockerized app. What do you think?

**Comment by tkopczuk** [comment]
I'd go with a dockerized app, just to go with what we're going to do anyway :)

**Comment by gabrieloczkowski** [comment]
Closing PR because we decided to maintain only dockerized version of pdf-generator-service.

**Pull request closed without merging**
